// Static reference data for the wire-recipient wizard.
//
// COUNTRIES   — ISO-3166-1 alpha-2 list (factual reference data).
// BANKS_BY_COUNTRY — curated short-lists of well-known retail/commercial banks per
// country, with an "Other" fallback row so any country always has at least one
// pickable option. The shape is intentionally minimal — name + optional swiftHint
// — so the wizard can show useful options without claiming to be a full BIC
// directory.

export type Country = { code: string; name: string };
export type BankRef = { name: string; swiftHint?: string };

export const COUNTRIES: Country[] = [
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "MX", name: "Mexico" },
  { code: "GB", name: "United Kingdom" },
  { code: "IE", name: "Ireland" },
  { code: "FR", name: "France" },
  { code: "DE", name: "Germany" },
  { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" },
  { code: "PT", name: "Portugal" },
  { code: "NL", name: "Netherlands" },
  { code: "BE", name: "Belgium" },
  { code: "LU", name: "Luxembourg" },
  { code: "CH", name: "Switzerland" },
  { code: "AT", name: "Austria" },
  { code: "DK", name: "Denmark" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "FI", name: "Finland" },
  { code: "IS", name: "Iceland" },
  { code: "PL", name: "Poland" },
  { code: "CZ", name: "Czech Republic" },
  { code: "SK", name: "Slovakia" },
  { code: "HU", name: "Hungary" },
  { code: "RO", name: "Romania" },
  { code: "BG", name: "Bulgaria" },
  { code: "GR", name: "Greece" },
  { code: "HR", name: "Croatia" },
  { code: "SI", name: "Slovenia" },
  { code: "EE", name: "Estonia" },
  { code: "LV", name: "Latvia" },
  { code: "LT", name: "Lithuania" },
  { code: "TR", name: "Türkiye" },
  { code: "UA", name: "Ukraine" },
  { code: "RS", name: "Serbia" },
  { code: "MT", name: "Malta" },
  { code: "CY", name: "Cyprus" },
  { code: "JP", name: "Japan" },
  { code: "CN", name: "China" },
  { code: "HK", name: "Hong Kong SAR" },
  { code: "TW", name: "Taiwan" },
  { code: "KR", name: "South Korea" },
  { code: "SG", name: "Singapore" },
  { code: "MY", name: "Malaysia" },
  { code: "TH", name: "Thailand" },
  { code: "VN", name: "Vietnam" },
  { code: "PH", name: "Philippines" },
  { code: "ID", name: "Indonesia" },
  { code: "IN", name: "India" },
  { code: "PK", name: "Pakistan" },
  { code: "BD", name: "Bangladesh" },
  { code: "LK", name: "Sri Lanka" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "New Zealand" },
  { code: "FJ", name: "Fiji" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "QA", name: "Qatar" },
  { code: "KW", name: "Kuwait" },
  { code: "BH", name: "Bahrain" },
  { code: "OM", name: "Oman" },
  { code: "IL", name: "Israel" },
  { code: "JO", name: "Jordan" },
  { code: "LB", name: "Lebanon" },
  { code: "EG", name: "Egypt" },
  { code: "MA", name: "Morocco" },
  { code: "TN", name: "Tunisia" },
  { code: "ZA", name: "South Africa" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "GH", name: "Ghana" },
  { code: "ET", name: "Ethiopia" },
  { code: "TZ", name: "Tanzania" },
  { code: "UG", name: "Uganda" },
  { code: "BR", name: "Brazil" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "PE", name: "Peru" },
  { code: "UY", name: "Uruguay" },
  { code: "EC", name: "Ecuador" },
  { code: "VE", name: "Venezuela" },
  { code: "CR", name: "Costa Rica" },
  { code: "PA", name: "Panama" },
  { code: "DO", name: "Dominican Republic" },
  { code: "GT", name: "Guatemala" },
  { code: "JM", name: "Jamaica" },
  { code: "BS", name: "Bahamas" },
  { code: "BB", name: "Barbados" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "RU", name: "Russia" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "GE", name: "Georgia" },
  { code: "AM", name: "Armenia" },
  { code: "AZ", name: "Azerbaijan" },
];

const OTHER: BankRef = { name: "Other (type bank name)" };

const US_BANKS: BankRef[] = [
  { name: "JPMorgan Chase Bank, N.A." },
  { name: "Bank of America, N.A." },
  { name: "Wells Fargo Bank, N.A." },
  { name: "Citibank, N.A." },
  { name: "U.S. Bank, N.A." },
  { name: "PNC Bank, N.A." },
  { name: "Truist Bank" },
  { name: "Capital One, N.A." },
  { name: "TD Bank, N.A." },
  { name: "Goldman Sachs Bank USA" },
  { name: "Charles Schwab Bank" },
  { name: "Ally Bank" },
  { name: "Fifth Third Bank" },
  { name: "Citizens Bank, N.A." },
  { name: "KeyBank, N.A." },
  { name: "First Republic Bank" },
  { name: "Silicon Valley Bank" },
  { name: "Regions Bank" },
  { name: "Bank of New York Mellon" },
  { name: "M&T Bank" },
  OTHER,
];

export const BANKS_BY_COUNTRY: Record<string, BankRef[]> = {
  US: US_BANKS,
  CA: [
    { name: "Royal Bank of Canada" },
    { name: "Toronto-Dominion Bank" },
    { name: "Bank of Paxnova Scotia" },
    { name: "Bank of Montreal" },
    { name: "Canadian Imperial Bank of Commerce" },
    { name: "National Bank of Canada" },
    { name: "HSBC Bank Canada" },
    { name: "Desjardins" },
    OTHER,
  ],
  MX: [
    { name: "BBVA México" },
    { name: "Banorte" },
    { name: "Santander México" },
    { name: "Citibanamex" },
    { name: "HSBC México" },
    { name: "Scotiabank México" },
    OTHER,
  ],
  GB: [
    { name: "HSBC UK Bank plc" },
    { name: "Barclays Bank UK plc" },
    { name: "Lloyds Bank plc" },
    { name: "NatWest Group" },
    { name: "Santander UK plc" },
    { name: "Standard Chartered Bank" },
    { name: "Nationwide Building Society" },
    { name: "Monzo Bank" },
    { name: "Starling Bank" },
    OTHER,
  ],
  IE: [
    { name: "Bank of Ireland" },
    { name: "AIB Group" },
    { name: "Permanent TSB" },
    OTHER,
  ],
  FR: [
    { name: "BNP Paribas" },
    { name: "Crédit Agricole" },
    { name: "Société Générale" },
    { name: "BPCE" },
    { name: "Crédit Mutuel" },
    { name: "La Banque Postale" },
    OTHER,
  ],
  DE: [
    { name: "Deutsche Bank AG" },
    { name: "Commerzbank AG" },
    { name: "DZ Bank AG" },
    { name: "KfW" },
    { name: "ING-DiBa AG" },
    { name: "N26 Bank" },
    OTHER,
  ],
  IT: [
    { name: "Intesa Sanpaolo" },
    { name: "UniCredit" },
    { name: "Banco BPM" },
    { name: "Monte dei Paschi di Siena" },
    OTHER,
  ],
  ES: [
    { name: "Banco Santander" },
    { name: "BBVA" },
    { name: "CaixaBank" },
    { name: "Banco Sabadell" },
    OTHER,
  ],
  NL: [
    { name: "ING Bank N.V." },
    { name: "Rabobank" },
    { name: "ABN AMRO Bank N.V." },
    { name: "Bunq" },
    OTHER,
  ],
  CH: [
    { name: "UBS AG" },
    { name: "Credit Suisse (now UBS)" },
    { name: "Raiffeisen Schweiz" },
    { name: "PostFinance" },
    { name: "Julius Baer" },
    OTHER,
  ],
  AT: [
    { name: "Erste Group Bank" },
    { name: "Raiffeisen Bank International" },
    OTHER,
  ],
  BE: [
    { name: "KBC Group" },
    { name: "BNP Paribas Fortis" },
    { name: "Belfius Bank" },
    OTHER,
  ],
  LU: [{ name: "Banque et Caisse d'Épargne de l'État" }, OTHER],
  DK: [{ name: "Danske Bank" }, { name: "Nordea Bank" }, { name: "Nykredit" }, OTHER],
  SE: [
    { name: "Nordea Bank Sweden" },
    { name: "SEB" },
    { name: "Svenska Handelsbanken" },
    { name: "Swedbank" },
    OTHER,
  ],
  NO: [{ name: "DNB Bank" }, { name: "Nordea Bank Norway" }, OTHER],
  FI: [{ name: "OP Financial Group" }, { name: "Nordea Bank Finland" }, OTHER],
  PT: [
    { name: "Caixa Geral de Depósitos" },
    { name: "Banco BPI" },
    { name: "Millennium BCP" },
    OTHER,
  ],
  JP: [
    { name: "MUFG Bank, Ltd." },
    { name: "Sumitomo Mitsui Banking Corporation" },
    { name: "Mizuho Bank, Ltd." },
    { name: "Japan Post Bank" },
    { name: "Resona Bank" },
    OTHER,
  ],
  CN: [
    { name: "Industrial and Commercial Bank of China" },
    { name: "China Construction Bank" },
    { name: "Agricultural Bank of China" },
    { name: "Bank of China" },
    { name: "Bank of Communications" },
    OTHER,
  ],
  HK: [
    { name: "HSBC Hong Kong" },
    { name: "Hang Seng Bank" },
    { name: "Bank of China (Hong Kong)" },
    { name: "Standard Chartered Hong Kong" },
    OTHER,
  ],
  KR: [
    { name: "KB Kookmin Bank" },
    { name: "Shinhan Bank" },
    { name: "Hana Bank" },
    { name: "Woori Bank" },
    OTHER,
  ],
  SG: [
    { name: "DBS Bank" },
    { name: "OCBC Bank" },
    { name: "United Overseas Bank" },
    { name: "Standard Chartered Singapore" },
    OTHER,
  ],
  AU: [
    { name: "Commonwealth Bank of Australia" },
    { name: "Westpac Banking Corporation" },
    { name: "Australia and New Zealand Banking Group" },
    { name: "National Australia Bank" },
    { name: "Macquarie Bank" },
    OTHER,
  ],
  NZ: [
    { name: "ANZ Bank New Zealand" },
    { name: "ASB Bank" },
    { name: "Bank of New Zealand" },
    { name: "Westpac New Zealand" },
    OTHER,
  ],
  IN: [
    { name: "State Bank of India" },
    { name: "HDFC Bank" },
    { name: "ICICI Bank" },
    { name: "Axis Bank" },
    { name: "Kotak Mahindra Bank" },
    { name: "Punjab National Bank" },
    OTHER,
  ],
  AE: [
    { name: "Emirates NBD" },
    { name: "First Abu Dhabi Bank" },
    { name: "Abu Dhabi Commercial Bank" },
    { name: "Mashreq Bank" },
    OTHER,
  ],
  SA: [
    { name: "Saudi National Bank" },
    { name: "Al Rajhi Bank" },
    { name: "Riyad Bank" },
    OTHER,
  ],
  IL: [
    { name: "Bank Hapoalim" },
    { name: "Bank Leumi" },
    { name: "Israel Discount Bank" },
    OTHER,
  ],
  ZA: [
    { name: "Standard Bank Group" },
    { name: "FirstRand Bank (FNB)" },
    { name: "Absa Group" },
    { name: "Nedbank" },
    OTHER,
  ],
  NG: [
    { name: "Access Bank" },
    { name: "Zenith Bank" },
    { name: "Guaranty Trust Bank" },
    { name: "First Bank of Nigeria" },
    OTHER,
  ],
  KE: [
    { name: "Kenya Commercial Bank" },
    { name: "Equity Bank" },
    { name: "Co-operative Bank of Kenya" },
    OTHER,
  ],
  BR: [
    { name: "Itaú Unibanco" },
    { name: "Banco do Brasil" },
    { name: "Bradesco" },
    { name: "Santander Brasil" },
    { name: "Caixa Econômica Federal" },
    { name: "Nubank" },
    OTHER,
  ],
  AR: [
    { name: "Banco de la Nación Argentina" },
    { name: "Banco Galicia" },
    { name: "Banco Santander Río" },
    OTHER,
  ],
  CL: [
    { name: "Banco de Chile" },
    { name: "Banco Santander Chile" },
    { name: "BancoEstado" },
    OTHER,
  ],
  CO: [
    { name: "Bancolombia" },
    { name: "Banco de Bogotá" },
    { name: "Davivienda" },
    OTHER,
  ],
};

export function banksForCountry(code: string): BankRef[] {
  return BANKS_BY_COUNTRY[code] ?? [OTHER];
}
